<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run()
    {
        DB::table('products')->insert([
            [
                'name' => 'Genuine Leather Bracelet',
                'brand' => 'Brand 1',
                'price' => 100.00,
                'image' => 'images/team1.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Luxury Silver Ring',
                'brand' => 'Brand 2',
                'price' => 150.00,
                'image' => 'images/team2.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Heart Pendant Necklace',
                'brand' => 'Brand 3',
                'price' => 200.00,
                'image' => 'images/team3.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Elegant Classic Watch',
                'brand' => 'Brand 4',
                'price' => 250.00,
                'image' => 'images/team4.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fine Jewelry Set',
                'brand' => 'Brand 5',
                'price' => 300.00,
                'image' => 'images/team5.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Crystal Embellished Brooch',
                'brand' => 'Brand 6',
                'price' => 80.00,
                'image' => 'images/team6.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Delicate Gold Earrings',
                'brand' => 'Brand 7',
                'price' => 120.00,
                'image' => 'images/team7.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Elegant Neck Chain',
                'brand' => 'Brand 8',
                'price' => 180.00,
                'image' => 'images/team8.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sapphire and Diamond Ring',
                'brand' => 'Brand 9',
                'price' => 500.00,
                'image' => 'images/team9.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gold-Plated Cufflinks',
                'brand' => 'Brand 10',
                'price' => 70.00,
                'image' => 'images/team10.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Platinum Necklace',
                'brand' => 'Brand 11',
                'price' => 600.00,
                'image' => 'images/team11.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Silver Pendant with Gemstones',
                'brand' => 'Brand 12',
                'price' => 350.00,
                'image' => 'images/team12.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Minimalist Gold Watch',
                'brand' => 'Brand 13',
                'price' => 220.00,
                'image' => 'images/team13.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Exclusive Diamond Earrings',
                'brand' => 'Brand 14',
                'price' => 900.00,
                'image' => 'images/team14.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Luxury Crystal Bracelet',
                'brand' => 'Brand 15',
                'price' => 150.00,
                'image' => 'images/team15.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vintage Silver Ring',
                'brand' => 'Brand 16',
                'price' => 130.00,
                'image' => 'images/team16.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rose Gold Necklace',
                'brand' => 'Brand 17',
                'price' => 320.00,
                'image' => 'images/team17.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Black Onyx Brooch',
                'brand' => 'Brand 18',
                'price' => 95.00,
                'image' => 'images/team18.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Luxury Gemstone Earrings',
                'brand' => 'Brand 19',
                'price' => 400.00,
                'image' => 'images/team19.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Charming Silver Bracelet',
                'brand' => 'Brand 20',
                'price' => 110.00,
                'image' => 'images/team20.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gleaming Sapphire Pendant',
                'brand' => 'Brand 21',
                'price' => 250.00,
                'image' => 'images/team21.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Royal Gold Ring',
                'brand' => 'Brand 22',
                'price' => 350.00,
                'image' => 'images/team22.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Elegant Crystal Earrings',
                'brand' => 'Brand 23',
                'price' => 180.00,
                'image' => 'images/team23.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Diamond-studded Pendant',
                'brand' => 'Brand 24',
                'price' => 600.00,
                'image' => 'images/team24.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Timeless Silver Watch',
                'brand' => 'Brand 25',
                'price' => 400.00,
                'image' => 'images/team25.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Exquisite Gold Earrings',
                'brand' => 'Brand 26',
                'price' => 450.00,
                'image' => 'images/team26.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sophisticated Pearl Necklace',
                'brand' => 'Brand 27',
                'price' => 350.00,
                'image' => 'images/team27.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sterling Silver Bracelet',
                'brand' => 'Brand 28',
                'price' => 250.00,
                'image' => 'images/team28.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fine Gold Cufflinks',
                'brand' => 'Brand 29',
                'price' => 200.00,
                'image' => 'images/team29.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Classic Gemstone Necklace',
                'brand' => 'Brand 30',
                'price' => 280.00,
                'image' => 'images/team30.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Brilliant Diamond Bracelet',
                'brand' => 'Brand 31',
                'price' => 750.00,
                'image' => 'images/team31.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Exquisite Platinum Ring',
                'brand' => 'Brand 32',
                'price' => 950.00,
                'image' => 'images/team32.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        
    
   }    
}

